export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"博客主页","icon":"home","type":"home","readingTime":{"minutes":0.61,"words":182},"excerpt":""},["/index.html","/README.md"]],
  ["v-62ef9a50","/blog/article10.html",{"title":"文章 10","icon":"edit","type":"article","readingTime":{"minutes":0.11,"words":33},"excerpt":"文章 10 标题 2 这里是内容。 标题 3 这里是内容。","date":"2022-01-10T00:00:00.000Z","localizedDate":"2022年1月10日","category":["CategoryA","CategoryB"],"tag":["tag A","tag B"]},["/blog/article10","/blog/article10.md"]],
  ["v-5f85e912","/blog/article11.html",{"title":"文章 11","icon":"edit","type":"article","readingTime":{"minutes":0.11,"words":33},"excerpt":"文章 11 标题 2 这里是内容。 标题 3 这里是内容。","date":"2022-01-11T00:00:00.000Z","localizedDate":"2022年1月11日","category":["CategoryA","CategoryB"],"tag":["tag A","tag B"]},["/blog/article11","/blog/article11.md"]],
  ["v-5c1c37d4","/blog/article12.html",{"title":"文章 12","icon":"edit","type":"article","readingTime":{"minutes":0.12,"words":35},"excerpt":"文章 12 标题 2 这里是内容。 标题 3 这里是内容。","date":"2022-01-12T00:00:00.000Z","localizedDate":"2022年1月12日","category":["CategoryA","CategoryB"],"tag":["tag A","tag B"],"star":true},["/blog/article12","/blog/article12.md"]],
  ["v-3556efc2","/blog/article9.html",{"title":"文章 9","icon":"edit","type":"article","readingTime":{"minutes":0.11,"words":33},"excerpt":"文章 9 标题 2 这里是内容。 标题 3 这里是内容。","date":"2022-01-09T00:00:00.000Z","localizedDate":"2022年1月9日","category":["CategoryA","CategoryB"],"tag":["tag A","tag B"]},["/blog/article9","/blog/article9.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-3e5b7b84","/category/categorya/",{"title":"CategoryA 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/categorya/index.html"]],
  ["v-06bbb262","/tag/tag-a/",{"title":"tag A 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/tag-a/index.html"]],
  ["v-3e5b7ba3","/category/categoryb/",{"title":"CategoryB 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/categoryb/index.html"]],
  ["v-06bbb224","/tag/tag-b/",{"title":"tag B 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/tag-b/index.html"]],
]
